### ISSUE TITLE
ImportError: cannot import name 'localize_unit': Failing to launch the GUI

### ISSUE THREAD

**Issue by caniko** [SpikeInterface/spikeinterface-gui#21]
Hello

I have been getting into the `spikeinterface` ecosystem lately, and I am struggling to launch the GUI.

The import error is related to `spikeinterface.toolkit`:
```
 ╭─can@vianadasilva1 in ~ via  v3.8.12 (spike_gui) took 3m55s
 ╰─λ sigui
Traceback (most recent call last):
  File "/home/can/.pyenv/versions/spike_gui/bin/sigui", line 5, in <module>
    from spikeinterface_gui.main import run_mainwindow_cli
  File "/home/can/.pyenv/versions/3.8.12/envs/spike_gui/lib/python3.8/site-packages/spikeinterface_gui/__init__.py", line 8, in <module>
    from .mainwindow import MainWindow
  File "/home/can/.pyenv/versions/3.8.12/envs/spike_gui/lib/python3.8/site-packages/spikeinterface_gui/mainwindow.py", line 6, in <module>
    from .controller import SpikeinterfaceController
  File "/home/can/.pyenv/versions/3.8.12/envs/spike_gui/lib/python3.8/site-packages/spikeinterface_gui/controller.py", line 7, in <module>
    from spikeinterface.toolkit import (get_template_extremum_channel, get_template_channel_sparsity,
ImportError: cannot import name 'localize_unit' from 'spikeinterface.toolkit' (/home/can/.pyenv/versions/3.8.12/envs/spike_gui/lib/python3.8/site-packages/spikeinterface/toolkit/__init__.py)
```

I used `PySide6`, but I don't think it matters for the exception that is being thrown.

FYI, the same exception is also thrown in this situation:
```
import spikeinterface_gui

# This cerate a Qt app
app = spikeinterface_gui.mkQApp() 
# reload the waveform folder
we = si.WaveformExtractor.load_from_folder("/home/can/ePhys/waveforms/119_2022-02-10_13-43-33_1/")
# create the mainwindow and show
win = spikeinterface_gui.MainWindow(we)
win.show()
# run the main Qt6 loop
app.exec_()
```

**Comment by samuelgarcia** [comment]
#20 fixed it already but it was after the relase so you need to install from source.

**Comment by caniko** [comment]
> #20 fixed it already but it was after the relase so you need to install from source.

Installing from source worked a few days ago on my computer, Arch Linux.

5 days later, I tried to install on a Windows PC in the lab; got this error (installed from source also):
``` shell
(si_env) PS C:\Users\user-adm\Documents\spikeinterface\spikeinterface-gui> sigui C:\Users\user-adm\Documents\oe_data\waveforms\119_2022-02-11_15-54-45_3
Traceback (most recent call last):
  File "C:\Users\user-adm\miniconda3\envs\si_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user-adm\miniconda3\envs\si_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user-adm\miniconda3\envs\si_env\Scripts\sigui.exe\__main__.py", line 4, in <module>
  File "C:\Users\user-adm\miniconda3\envs\si_env\lib\site-packages\spikeinterface_gui\__init__.py", line 8, in <module>
    from .mainwindow import MainWindow
  File "C:\Users\user-adm\miniconda3\envs\si_env\lib\site-packages\spikeinterface_gui\mainwindow.py", line 6, in <module>
    from .controller import SpikeinterfaceController
  File "C:\Users\user-adm\miniconda3\envs\si_env\lib\site-packages\spikeinterface_gui\controller.py", line 7, in <module>
    from spikeinterface.toolkit import (get_template_extremum_channel, get_template_channel_sparsity,
ImportError: cannot import name 'localize_units' from 'spikeinterface.toolkit' (C:\Users\user-adm\miniconda3\envs\si_env\lib\site-packages\spikeinterface\toolkit\__init__.py)
```

**Comment by samuelgarcia** [comment]
You also need to update spikeinetrface to new version or from source.
Sorry for this package misalignement.
I will amke a realse now to avoid this.
