### ISSUE TITLE
Errors in running spikeinterface_gui on Mac 

### ISSUE THREAD

**Issue by rohanmalige** [SpikeInterface/spikeinterface-gui#62]
@mandarmp and I were trying to run the spikeinterface_gui locally on MacOS, we are using Xquartz to run the GUI and the error we got is: 
rohan@rohans-mbp-3 ~ % sigui /Users/rohan/Documents/Research/MEA_Analysis/AnalyzedData/CDKL5/CDKL5/230310/16757/Network/000033/waveforms_good
Traceback (most recent call last):
  File "/Users/rohan/Library/Python/3.11/bin/sigui", line 5, in <module>
    from spikeinterface_gui.main import run_mainwindow_cli
  File "/Users/rohan/Library/Python/3.11/lib/python/site-packages/spikeinterface_gui/__init__.py", line 8, in <module>
    from .mainwindow import MainWindow
  File "/Users/rohan/Library/Python/3.11/lib/python/site-packages/spikeinterface_gui/mainwindow.py", line 170, in <module>
    'right' : QT.Qt.RightDockWidgetArea,
              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Qt' has no attribute 'RightDockWidgetArea'. Did you mean: 'DockWidgetArea'?

Can you help us out with what steps we need to take to solve the issue?

**Comment by samuelgarcia** [comment]
Hi,
thanks for the feedback.
How did you installed QT ? Is it with anaconda ?
Do you PyQt5, PyQt6 or PySide6 ?

spikeinterface-gui is mainly tested on PySide6

**Comment by rohanmalige** [comment]
I installed QT without an anaconda. I installed PyQT6. Do you recommend using anaconda for mac? is PySide6 necessary for running the spikeinterface_gui?

**Comment by samuelgarcia** [comment]
It is PySide6 or PyQt6 or PyQt5. DO not try to install two of then on the same envirenoement it will be a total mess.
I have to admit that PyQt6 is not realy tested. Could you try to remove PyQt6 and use PyQt5 instead ?

**Comment by rohanmalige** [comment]
```rohan@Rohans-MacBook-Pro-3 ~ % sigui /Users/rohan/Documents/Research/MEA_Analysis/AnalyzedData/CDKL5/CDKL5/230310/16757/Network/000033/waveforms_good/waveforms/
Traceback (most recent call last):
  File "/Users/rohan/Library/Python/3.11/bin/sigui", line 8, in <module>
    sys.exit(run_mainwindow_cli())
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohan/Library/Python/3.11/lib/python/site-packages/spikeinterface_gui/main.py", line 34, in run_mainwindow_cli
    run_mainwindow(waveform_folder)
  File "/Users/rohan/Library/Python/3.11/lib/python/site-packages/spikeinterface_gui/main.py", line 14, in run_mainwindow
    we = WaveformExtractor.load_from_folder(waveform_folder)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohan/Library/Python/3.11/lib/python/site-packages/spikeinterface/core/waveform_extractor.py", line 176, in load_from_folder
    raise Exception("The recording could not be loaded. You can use the `with_recording=False` argument")
Exception: The recording could not be loaded. You can use the `with_recording=False` argument
```
I installed the PyQT5 instead of PyQt6, re-run the above command, and got the errors. Is there any specific way that the waveforms need to be stored?

**Comment by alejoe91** [comment]
@rohanmalige can you try with the main branch? We made a lot of updates and bug fixes recently
